using System.Text;
using PokemonPlatinumEngine.Battle.Effects;
using PokemonPlatinumEngine.Data;
using PokemonPlatinumEngine.Models;

namespace DataImporter;

/// <summary>Writes docs/mechanics/coverage.md: what the data holds and how much of it the engine runs.</summary>
public static class Coverage
{
    public static string Report(List<PokemonSpecies> species, List<MoveData> moves, List<AbilityDatabase.AbilityRecord> abilities, List<ItemData> items)
    {
        var implementedAbilities = AbilityEffectTable.Names.ToHashSet(StringComparer.OrdinalIgnoreCase);
        var sb = new StringBuilder();
        void Line(string text = "") => sb.Append(text).Append('\n');

        Line("# Coverage");
        Line();
        Line("Generated by `tools/DataImporter` (don't edit by hand): what the game data holds and how much of it the battle engine runs. " +
             "Generations 1–4 use Platinum's own data; later generations use their newest games' data. Plan 06 turns the gaps below into code.");
        Line();

        Line("## By generation");
        Line();
        Line("| Generation | Species | Moves | Moves fully run | Moves partly run | Moves that do nothing yet | Abilities | Abilities with an effect |");
        Line("| --- | --- | --- | --- | --- | --- | --- | --- |");
        foreach (int gen in species.Select(s => s.Generation).Concat(moves.Select(m => m.Generation)).Distinct().Order())
        {
            var genMoves = moves.Where(m => m.Generation == gen).ToList();
            var genAbilities = abilities.Where(a => a.Generation == gen).ToList();
            Line($"| {gen} | {species.Count(s => s.Generation == gen)} | {genMoves.Count} | {genMoves.Count(m => m.Support == MoveEffectSupport.Full)} | " +
                 $"{genMoves.Count(m => m.Support == MoveEffectSupport.Partial)} | {genMoves.Count(m => m.Support == MoveEffectSupport.None)} | " +
                 $"{genAbilities.Count} | {genAbilities.Count(a => implementedAbilities.Contains(a.Name))} |");
        }
        Line($"| All | {species.Count} | {moves.Count} | {moves.Count(m => m.Support == MoveEffectSupport.Full)} | " +
             $"{moves.Count(m => m.Support == MoveEffectSupport.Partial)} | {moves.Count(m => m.Support == MoveEffectSupport.None)} | " +
             $"{abilities.Count} | {abilities.Count(a => implementedAbilities.Contains(a.Name))} |");
        Line();

        Line("## Move effects still to write");
        Line();
        Line("*Partly run*: the move hits (or its stat change, status or healing happens) but its own effect is missing. " +
             "*Does nothing yet*: using it says \"But nothing happened!\", and trainers only pick it when they have nothing else.");
        Line();
        Line("| Effect | Support | Moves |");
        Line("| --- | --- | --- |");
        foreach (var group in moves.Where(m => m.Effect != null).GroupBy(m => (m.Effect, m.Support))
                     .OrderByDescending(g => g.Count()).ThenBy(g => g.Key.Effect))
        {
            string support = group.Key.Support == MoveEffectSupport.Partial ? "partly run" : "does nothing yet";
            Line($"| {group.Key.Effect} | {support} | {string.Join(", ", group.Select(m => m.Name))} |");
        }
        Line();

        Line("## Abilities without an effect");
        Line();
        foreach (var gen in abilities.Where(a => !implementedAbilities.Contains(a.Name)).GroupBy(a => a.Generation).OrderBy(g => g.Key))
            Line($"- Generation {gen.Key} ({gen.Count()}): {string.Join(", ", gen.Select(a => a.Name))}");
        Line();

        Line("## Items");
        Line();
        var held = items.Where(i => i.HoldEffect != null).ToList();
        Line($"{items.Count} items: {items.Count(i => i.Id < 1000)} from Platinum and {items.Count(i => i.Id >= 1000)} from later games " +
             "(those have no hold effect name yet). What using an item does runs for the effect types the bag and battle know " +
             "(`HealHP`, `Revive`, `FullRestore`, `LevelUp`, `CatchPokemon`); balls with a condition (Net, Dusk, Timer and the like) " +
             "catch like a Poké Ball for now.");
        Line();
        Line($"Platinum items with a hold effect: {held.Count}, of which {held.Count(HeldItemEffects.IsHoldable)} work in battle. Not yet:");
        Line();
        foreach (var group in held.Where(i => !HeldItemEffects.IsHoldable(i)).GroupBy(i => i.HoldEffect).OrderBy(g => g.Key))
            Line($"- {group.Key}: {string.Join(", ", group.Select(i => i.Name))}");
        Line();

        Line("## Evolutions");
        Line();
        var evolutions = species.SelectMany(s => s.Evolutions ?? new()).ToList();
        Line($"{evolutions.Count} evolutions. `Models/Evolution.cs` has a rule for every method (docs/mechanics/evolution.md explains each); " +
             "some can't be met in the game until something else is built:");
        Line();
        Line("| Method | Evolutions | Set off by | Waits for |");
        Line("| --- | --- | --- | --- |");
        foreach (var group in evolutions.GroupBy(e => e.Method).OrderByDescending(g => g.Count()).ThenBy(g => g.Key.ToString()))
        {
            string trigger = Evolution.TriggerOf(group.Key) switch
            {
                EvolutionTrigger.LevelUp => "a level-up",
                EvolutionTrigger.UseItem => "an item used on it",
                EvolutionTrigger.Trade => "a trade",
                EvolutionTrigger.Spin => "the player spinning",
                _ => group.Key == EvolutionMethod.LevelShedinja ? "Nincada evolving" : "nothing yet"
            };
            Line($"| {group.Key} | {group.Count()} | {trigger} | {WaitsFor(group.Key)} |");
        }
        return sb.ToString();
    }

    /// <summary>What has to exist before an evolution method can be met in play (empty: it already can).</summary>
    private static string WaitsFor(EvolutionMethod method) => method switch
    {
        EvolutionMethod.Trade or EvolutionMethod.TradeHoldingItem or EvolutionMethod.TradeWithSpecies
            => "trading (plan 07 · O5; in-game trades in plan 06 · R12). A Linking Cord used on the Pokémon does the same today",
        EvolutionMethod.Beauty => "Poffins (plan 06 · R14)",
        EvolutionMethod.LevelAtLocation => "maps with a Moss Rock, an Ice Rock or a magnetic field (plan 01)",
        EvolutionMethod.LevelInRain => "weather in the field (plan 01)",
        EvolutionMethod.LevelWithItemsInBag => "a way to collect the items (plan 03 · D12)",
        EvolutionMethod.Other => "a rule of its own",
        _ => ""
    };
}
